### ISSUE TITLE
`[err, foo]` instead of `[foo, err]`

### ISSUE THREAD

**Issue by vjpr** [xobotyi/await-of#8]
**Do you want to request a _feature_ or report a _bug_?**

Feature

---

JS callback convention is like this. Can you provide an option to change it to this. Otherwise create library.

**Comment by xobotyi** [comment]
Havent heard about that convention..

Here possibly thrown errors are swallowed and put into the `err` parameter, it is way safer for developer to have parameters exact in that order because it is **way easier** to forget handle the error in case of `[foo, err]`.
`[err, foo]` order made exactly to remind the developer like 'hey, errors are possible here'. This aproach used widely in libs/code that silently returns an error instead of throwing it.
